/*Creación de tablas*/

CREATE TABLE CLIENTE(
  ID_CLIENTE INT,
  NOMBRE VARCHAR2(20) NOT NULL,
  APELLIDO VARCHAR2(20),
  DIRECCION VARCHAR(100),
  TELEFONO VARCHAR2(10),
  EMAIL VARCHAR2(50)
);

CREATE TABLE VEHICULO(
  VIN CHAR(17),
  PLACA CHAR(6) NOT NULL,
  MARCA VARCHAR2(20) NOT NULL,
  MODELO VARCHAR2(20) NOT NULL,
  ANNO CHAR(4),
  COLOR VARCHAR2(10),
  ID_CLIENTE INT
);

CREATE TABLE EMPLEADO (
  ID_EMPLEADO INT,
  NOMBRE VARCHAR(20) NOT NULL,
  APELLIDO VARCHAR2(20),
  TIPO VARCHAR2(20) NOT NULL,
  ESTADO CHAR(1) NOT NULL,
  CONTRASENA VARCHAR2(15) NOT NULL
);

CREATE TABLE PROVEEDOR (
  ID_PROVEEDOR INT,
  NOMBRE VARCHAR2(20) NOT NULL,
  APELLIDO VARCHAR2(20),
  PAIS VARCHAR2(15) NOT NULL,
  PROVINCIA VARCHAR2(15),
  TELEFONO VARCHAR2(10) NOT NULL,
  DIRECCION VARCHAR2(100)
);

CREATE TABLE STOCK(
  ID_REPUESTO INT,
  NOMBRE VARCHAR2(20) NOT NULL,
  CANTIDAD NUMBER NOT NULL,
  PRECIO NUMBER NOT NULL,
  ID_PROVEEDOR INT
);

CREATE TABLE HOJADEPARTE(
  ID_HOJA INT,
  HORAYFECHAENTRADA TIMESTAMP NOT NULL,
  HORAYFECHASALIDA TIMESTAMP,
  MANODEOBRA NUMBER,
  DETALLE VARCHAR2 (500),
  VIN CHAR(17),
  ID_EMPLEADO INT,
  ID_REPUESTO INT
);

CREATE TABLE FACTURA(
  ID_FACTURA INT,
  FECHA DATE NOT NULL,
  ID_CLIENTE INT
);

CREATE TABLE DETALLE_FACTURA(
  ID_DETALLE_FACTURA INT,
  ID_FACTURA INT,
  ID_REPUESTO INT,
  PRECIO NUMBER,
  CANTIDAD NUMBER,
  MANODEOBRA NUMBER,
  ID_HOJA INT
);

/*Creación PK y FK*/
--Primary key
--ID_CLIENTE
ALTER TABLE CLIENTE  
MODIFY (ID_CLIENTE NOT NULL);

ALTER TABLE CLIENTE
ADD CONSTRAINT CLIENTE_PK PRIMARY KEY 
(
  ID_CLIENTE 
)
ENABLE;

--VIN
ALTER TABLE VEHICULO
ADD CONSTRAINT VEHICULO_PK PRIMARY KEY 
(
  VIN 
)
ENABLE;

--EMPLEADO
ALTER TABLE EMPLEADO  
MODIFY (ID_EMPLEADO NOT NULL);

ALTER TABLE EMPLEADO
ADD CONSTRAINT EMPLEADO_PK PRIMARY KEY 
(
  ID_EMPLEADO 
)
ENABLE;

--PROVEEDOR
ALTER TABLE PROVEEDOR  
MODIFY (ID_PROVEEDOR NOT NULL);

ALTER TABLE PROVEEDOR
ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY 
(
  ID_PROVEEDOR 
)
ENABLE;

--STOCK
ALTER TABLE STOCK  
MODIFY (ID_REPUESTO NOT NULL);

ALTER TABLE STOCK
ADD CONSTRAINT STOCK_PK PRIMARY KEY 
(
  ID_REPUESTO 
)
ENABLE;

--HOJA DE PARTE
ALTER TABLE HOJADEPARTE  
MODIFY (ID_HOJA NOT NULL);

ALTER TABLE HOJADEPARTE
ADD CONSTRAINT HOJADEPARTE_PK PRIMARY KEY 
(
  ID_HOJA 
)
ENABLE;

--FACTURA
ALTER TABLE FACTURA  
MODIFY (ID_FACTURA NOT NULL);

ALTER TABLE FACTURA
ADD CONSTRAINT FACTURA_PK PRIMARY KEY 
(
  ID_FACTURA 
)
ENABLE;

--DETALLE FACTURA
ALTER TABLE DETALLE_FACTURA  
MODIFY (ID_DETALLE_FACTURA NOT NULL);

ALTER TABLE DETALLE_FACTURA  
MODIFY (ID_FACTURA NOT NULL);

ALTER TABLE DETALLE_FACTURA
ADD CONSTRAINT DETALLE_FACTURA_PK PRIMARY KEY 
(
  ID_DETALLE_FACTURA 
)
ENABLE;


/*FOREING KEY*/

--CLIENTE A VEHICULO
ALTER TABLE VEHICULO
ADD CONSTRAINT CLIENTE_VEHICULO_FK FOREIGN KEY
(
  ID_CLIENTE
)
REFERENCES CLIENTE
(
  ID_CLIENTE 
)
ENABLE;

--VEHICULO A HOJA DE PARTE
ALTER TABLE HOJADEPARTE
ADD CONSTRAINT VEHICULO_HOJADEPARTE_FK FOREIGN KEY
(
  VIN
)
REFERENCES VEHICULO
(
  VIN
)
ENABLE;

--EMPLEADO A HOJA DE PARTE
ALTER TABLE HOJADEPARTE
ADD CONSTRAINT EMPLEADO_HOJADEPARTE_FK FOREIGN KEY
(
  ID_EMPLEADO
)
REFERENCES EMPLEADO
(
  ID_EMPLEADO 
)
ENABLE;

-- HOJA DE PARTE A DETALLE FACTURA 
ALTER TABLE DETALLE_FACTURA
ADD CONSTRAINT HOJADEPARTE_DETALLEFACTURA_FK FOREIGN KEY
(
  ID_HOJA
)
REFERENCES HOJADEPARTE
(
  ID_HOJA 
)
ENABLE;

-- CLIENTE A FACTURA
ALTER TABLE FACTURA
ADD CONSTRAINT CLIENTE_FACTURA_FK FOREIGN KEY
(
  ID_CLIENTE
)
REFERENCES CLIENTE
(
  ID_CLIENTE 
)
ENABLE;

--FACTURA A DETALLE FACTURA
ALTER TABLE DETALLE_FACTURA
ADD CONSTRAINT FACTURA_DETALLEFACTURA_FK FOREIGN KEY
(
  ID_FACTURA
)
REFERENCES FACTURA
(
  ID_FACTURA
)
ENABLE;

-- PROVEEDOR A STOCK

ALTER TABLE STOCK
ADD CONSTRAINT PROVEEDOR_STOCK_FK FOREIGN KEY
(
  ID_PROVEEDOR
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR
)
ENABLE;

--STOCK A DETALLE FACTURA

ALTER TABLE DETALLE_FACTURA
ADD CONSTRAINT STOCK_DETALLEFACTURA_FK FOREIGN KEY
(
  ID_REPUESTO
)
REFERENCES STOCK
(
  ID_REPUESTO
)
ENABLE;

/********Procedimientos Almacenados************/
-- Nuevo Cliente

CREATE or REPLACE PROCEDURE SP_CLIENTE_NUEVO 
(
  ID_CLIENTE IN INT, NOMBRE IN VARCHAR2, APELLIDO IN VARCHAR2, DIRECCION IN VARCHAR2,
  TELEFONO IN VARCHAR2, EMAIL IN VARCHAR2
) AS 
BEGIN
 INSERT INTO CLIENTE 
 VALUES(ID_CLIENTE, NOMBRE, APELLIDO, DIRECCION, TELEFONO, EMAIL);
END SP_CLIENTE_NUEVO;
/

--Nuevo Vehiculo

CREATE or REPLACE PROCEDURE SP_VEHICULO_NUEVO 
(
  VIN IN CHAR, PLACA IN CHAR, MARCA IN VARCHAR2, MODELO IN VARCHAR2,
  ANNO IN CHAR, COLOR IN VARCHAR2, ID_CLIENTE IN INT
) AS 
BEGIN
 INSERT INTO VEHICULO
 VALUES(VIN, PLACA, MARCA, MODELO, ANNO, COLOR, ID_CLIENTE);
END SP_VEHICULO_NUEVO;
/

-- Nuevo Empleado

CREATE or REPLACE PROCEDURE SP_EMPLEADO_NUEVO 
(
  ID_EMPLEADO IN INT, NOMBRE IN VARCHAR2, APELLIDO IN VARCHAR2, TIPO IN VARCHAR2,
  ESTADO IN CHAR, CONTRASENA IN VARCHAR2
) AS 
BEGIN
 INSERT INTO EMPLEADO
 VALUES(ID_EMPLEADO, NOMBRE, APELLIDO, TIPO, ESTADO, CONTRASENA);
END SP_EMPLEADO_NUEVO;
/

--Nuevo Proveedor

CREATE or REPLACE PROCEDURE SP_PROVEEDOR_NUEVO 
(
  ID_PROVEEDOR IN INT, NOMBRE IN VARCHAR2, APELLIDO IN VARCHAR2, PAIS IN VARCHAR2,
  PROVINCIA IN VARCHAR2, TELEFONO IN VARCHAR2, DIRECCION IN VARCHAR2
) AS 
BEGIN
 INSERT INTO PROVEEDOR
 VALUES(ID_PROVEEDOR, NOMBRE, APELLIDO, PAIS, PROVINCIA, TELEFONO, DIRECCION);
END SP_PROVEEDOR_NUEVO;
/

select * from cliente